---
name: "Pedido de funcionalidade"
description: "Sugira uma ideia para este projeto"
body:
- type: markdown
  attributes:
    value: Antes de abrir um novo pedido de funcionalidade, pesquise nos pedidos existentes para ver se outras pessoas já tiveram a mesma ideia.
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: Preenchi o template da melhor forma que pude.
        required: true
      - label: Este pedido trata de uma única funcionalidade (se você tem vários pedidos, abra uma issue para cada um).
        required: true
      - label: Este pedido não é duplicata de nenhum dos [pedidos anteriores](https://github.com/roquerodrigo/ha-metro-sp/issues?q=is%3Aissue).
        required: true

- type: textarea
  attributes:
    label: "O seu pedido está relacionado a um problema? Descreva."
    description: "Uma descrição clara e concisa do problema."
    placeholder: "Sempre me incomoda quando [...]"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Descreva a solução que você gostaria"
    description: "Uma descrição clara e concisa do que você quer que aconteça."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Descreva as alternativas que você considerou"
    description: "Uma descrição clara e concisa das soluções ou funcionalidades alternativas que você considerou."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Contexto adicional"
    description: "Adicione aqui qualquer outro contexto ou capturas de tela sobre o pedido."
  validations:
    required: true
